/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#370096",
        "surface-container-highest": "#dcdddc",
        "background": "#f7f6f5",
        "surface": "#f7f6f5",
        "primary-container": "#ff7a2c",
        "on-background": "#2e2f2f",
        "outline-variant": "#adadac",
        "surface-container": "#e8e8e7",
        "tertiary": "#652fe7",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#005d4f",
        "primary-dim": "#883700",
        "surface-tint": "#9b3f00",
        "on-surface-variant": "#5b5c5b",
        "secondary-container": "#68fadd",
        "error": "#b02500",
        "on-tertiary": "#f7f0ff",
        "secondary": "#006859",
        "surface-dim": "#d4d4d4",
        "inverse-surface": "#0d0e0e",
        "on-surface": "#2e2f2f",
        "error-container": "#f95630",
        "tertiary-container": "#b8a3ff",
        "primary-fixed-dim": "#f46800",
        "surface-bright": "#f7f6f5",
        "on-primary": "#fff0ea",
        "on-primary-container": "#401600",
        "surface-container-low": "#f1f1f0",
        "inverse-primary": "#fd6c00",
        "tertiary-fixed": "#b8a3ff",
        "inverse-on-surface": "#9d9d9c",
        "surface-container-high": "#e2e2e1",
        "primary-fixed": "#ff7a2c",
        "on-secondary": "#c2ffef",
        "primary": "#9b3f00",
        "outline": "#767776",
        "surface-variant": "#dcdddc",
        "secondary-fixed": "#68fadd",
        "on-secondary-fixed-variant": "#006859",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Be Vietnam Pro", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
}
